/**
 * WhatsApp AI Agent Service for KadaiGPT
 * Integrates with your existing WhatsApp number for automated notifications
 * Features: Stock alerts, Daily reports, Bill notifications, Query handling
 */

import realDataService from './realDataService'
import whatsappService from './whatsapp'

class WhatsAppAgentService {
    constructor() {
        this.ownerPhone = localStorage.getItem('kadai_owner_phone') || ''
        this.storeName = localStorage.getItem('kadai_store_name') || 'KadaiGPT Store'
        this.autoNotificationsEnabled = localStorage.getItem('kadai_wa_notifications') === 'true'
    }

    // ==================== CONFIGURATION ====================

    setOwnerPhone(phone) {
        this.ownerPhone = phone
        localStorage.setItem('kadai_owner_phone', phone)
    }

    enableAutoNotifications(enabled) {
        this.autoNotificationsEnabled = enabled
        localStorage.setItem('kadai_wa_notifications', enabled ? 'true' : 'false')
    }

    // ==================== STOCK ALERTS ====================

    async checkAndSendLowStockAlert() {
        if (!this.ownerPhone) return { success: false, error: 'Owner phone not configured' }

        try {
            const lowStockProducts = await realDataService.getLowStockProducts()

            if (lowStockProducts.length === 0) {
                return { success: true, message: 'No low stock items' }
            }

            const message = this.generateLowStockMessage(lowStockProducts)
            whatsappService.openWhatsApp(this.ownerPhone, message)

            return { success: true, count: lowStockProducts.length }
        } catch (error) {
            console.error('Low stock alert failed:', error)
            return { success: false, error: error.message }
        }
    }

    generateLowStockMessage(products) {
        const time = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
        const date = new Date().toLocaleDateString('en-IN')

        const productList = products.slice(0, 15).map(p =>
            `• *${p.name}*: ${p.stock} left (Min: ${p.minStock})`
        ).join('\n')

        return `⚠️ *LOW STOCK ALERT*
📍 ${this.storeName}
📅 ${date} at ${time}

The following items need restocking:

${productList}
${products.length > 15 ? `\n...and ${products.length - 15} more items` : ''}

*Action Required:* Please restock soon to avoid stockouts.

_Sent by KadaiGPT AI Agent_ 🤖`
    }

    // ==================== DAILY SUMMARY ====================

    async sendDailySummary() {
        if (!this.ownerPhone) return { success: false, error: 'Owner phone not configured' }

        try {
            const summary = await realDataService.getDailySummary()

            if (!summary) {
                return { success: false, error: 'Could not generate summary' }
            }

            const message = this.generateDailySummaryMessage(summary)
            whatsappService.openWhatsApp(this.ownerPhone, message)

            return { success: true }
        } catch (error) {
            console.error('Daily summary failed:', error)
            return { success: false, error: error.message }
        }
    }

    generateDailySummaryMessage(summary) {
        const today = new Date().toLocaleDateString('en-IN', {
            weekday: 'long',
            day: 'numeric',
            month: 'long',
            year: 'numeric'
        })

        const topProducts = summary.topSellingProducts?.slice(0, 5).map(p =>
            `  • ${p.name}: ${p.quantity || p.sold || 0} sold`
        ).join('\n') || '  No sales data yet'

        return `📊 *DAILY BUSINESS REPORT*
📍 ${this.storeName}
📅 ${today}

━━━━━━━━━━━━━━━━━━━━

💰 *SALES SUMMARY*
• Total Sales: *₹${summary.totalSales?.toLocaleString() || 0}*
• Bills Created: *${summary.billCount || 0}*
• Avg Bill Value: *₹${Math.round(summary.avgBillValue || 0)}*

📈 *PROFIT & LOSS*
• Revenue: ₹${summary.totalSales?.toLocaleString() || 0}
• Expenses: ₹${summary.totalExpenses?.toLocaleString() || 0}
• Net Profit: *₹${summary.netProfit?.toLocaleString() || 0}*

💳 *PAYMENT BREAKDOWN*
• Cash: ₹${summary.paymentBreakdown?.cash?.toLocaleString() || 0}
• UPI: ₹${summary.paymentBreakdown?.upi?.toLocaleString() || 0}
• Card: ₹${summary.paymentBreakdown?.card?.toLocaleString() || 0}
• Credit: ₹${summary.paymentBreakdown?.credit?.toLocaleString() || 0}

🏆 *TOP SELLING PRODUCTS*
${topProducts}

━━━━━━━━━━━━━━━━━━━━

_Generated by KadaiGPT AI Agent_ 🤖
_Reply with "HELP" for available commands_`
    }

    // ==================== BILL NOTIFICATIONS ====================

    sendBillCreatedNotification(bill) {
        if (!this.autoNotificationsEnabled || !this.ownerPhone) return

        const message = `🧾 *NEW BILL CREATED*
📍 ${this.storeName}

Invoice: *${bill.bill_number || bill.billNumber}*
Customer: ${bill.customer_name || bill.customerName || 'Walk-in'}
Amount: *₹${bill.total?.toLocaleString()}*
Payment: ${bill.payment_mode || bill.paymentMethod}
Time: ${new Date().toLocaleTimeString('en-IN')}

_KadaiGPT Notification_ 🤖`

        // Note: This opens WhatsApp, for actual automation you'd need WhatsApp Business API
        whatsappService.openWhatsApp(this.ownerPhone, message)
    }

    // ==================== EXPENSE NOTIFICATIONS ====================

    sendExpenseAlert(expense) {
        if (!this.autoNotificationsEnabled || !this.ownerPhone) return

        const message = `💸 *EXPENSE RECORDED*
📍 ${this.storeName}

Category: ${expense.category}
Description: ${expense.description}
Amount: *₹${expense.amount?.toLocaleString()}*
Date: ${new Date(expense.date || Date.now()).toLocaleDateString('en-IN')}

_KadaiGPT Notification_ 🤖`

        whatsappService.openWhatsApp(this.ownerPhone, message)
    }

    // ==================== QUERY RESPONSE TEMPLATES ====================

    generateQueryResponse(query) {
        const lowerQuery = query.toLowerCase()

        // Sales query
        if (lowerQuery.includes('sales') || lowerQuery.includes('revenue')) {
            return this.getSalesResponse()
        }

        // Stock query
        if (lowerQuery.includes('stock') || lowerQuery.includes('inventory')) {
            return this.getStockResponse()
        }

        // Bill query
        if (lowerQuery.includes('bill') || lowerQuery.includes('invoice')) {
            return this.getBillsResponse()
        }

        // Expense query
        if (lowerQuery.includes('expense') || lowerQuery.includes('cost')) {
            return this.getExpenseResponse()
        }

        // Help
        if (lowerQuery.includes('help') || lowerQuery.includes('commands')) {
            return this.getHelpMessage()
        }

        return null
    }

    async getSalesResponse() {
        const stats = await realDataService.getDashboardStats()
        return `📊 *SALES UPDATE*

Today's Sales: *₹${stats.todaySales?.toLocaleString() || 0}*
Bills Created: ${stats.todayBills || 0}
Average Bill: ₹${Math.round(stats.avgBillValue || 0)}

_Reply "REPORT" for full daily report_`
    }

    async getStockResponse() {
        const lowStock = await realDataService.getLowStockProducts()
        const products = await realDataService.getProducts()

        return `📦 *STOCK STATUS*

Total Products: ${products.length}
Low Stock Items: *${lowStock.length}* ⚠️
Out of Stock: ${products.filter(p => p.stock === 0).length} ❌

${lowStock.length > 0 ? `\n*Low Stock Items:*\n${lowStock.slice(0, 5).map(p => `• ${p.name}: ${p.stock}`).join('\n')}` : ''}

_Reply "RESTOCK" for full low stock list_`
    }

    async getBillsResponse() {
        const bills = await realDataService.getTodayBills()
        const totalRevenue = bills.reduce((sum, b) => sum + (b.total || 0), 0)

        return `🧾 *TODAY'S BILLS*

Bills Count: ${bills.length}
Total Revenue: *₹${totalRevenue.toLocaleString()}*

*Recent Bills:*
${bills.slice(0, 5).map(b => `• ${b.billNumber}: ₹${b.total}`).join('\n') || 'No bills yet'}

_Open app for full details_`
    }

    async getExpenseResponse() {
        const summary = await realDataService.getExpenseSummary()

        return `💸 *EXPENSE SUMMARY*

Total Expenses: *₹${summary.total?.toLocaleString() || 0}*
Transactions: ${summary.count || 0}

*By Category:*
${Object.entries(summary.byCategory || {}).map(([cat, amt]) => `• ${cat}: ₹${amt.toLocaleString()}`).join('\n') || 'No expenses recorded'}

_Reply "ADD EXPENSE" to record new expense_`
    }

    getHelpMessage() {
        return `🤖 *KADAIGPT AI AGENT*
_Available Commands:_

📊 *SALES* - Get today's sales
📦 *STOCK* - Check inventory status
🧾 *BILLS* - View today's bills
💸 *EXPENSES* - See expense summary
📈 *REPORT* - Full daily report
⚠️ *LOWSTOCK* - Low stock alert
🔔 *NOTIFY ON/OFF* - Toggle alerts

_Just type any command to get started!_

_Powered by KadaiGPT_ ✨`
    }

    // ==================== INCOME/EXPENSE SUMMARY ====================

    async sendIncomeExpenseSummary() {
        if (!this.ownerPhone) return { success: false, error: 'Owner phone not configured' }

        try {
            const [stats, expenses] = await Promise.all([
                realDataService.getDashboardStats(),
                realDataService.getExpenseSummary()
            ])

            const income = stats.todaySales || 0
            const expense = expenses.total || 0
            const profit = income - expense

            const message = `💹 *INCOME vs EXPENSE*
📍 ${this.storeName}
📅 ${new Date().toLocaleDateString('en-IN')}

━━━━━━━━━━━━━━━━━━━━

📈 *INCOME*
• Today's Sales: *₹${income.toLocaleString()}*
• Bills: ${stats.todayBills || 0}

📉 *EXPENSES*
• Total: *₹${expense.toLocaleString()}*
• Transactions: ${expenses.count || 0}

━━━━━━━━━━━━━━━━━━━━

${profit >= 0 ? '✅' : '⚠️'} *NET PROFIT: ₹${profit.toLocaleString()}*

_KadaiGPT AI Agent_ 🤖`

            whatsappService.openWhatsApp(this.ownerPhone, message)
            return { success: true }
        } catch (error) {
            return { success: false, error: error.message }
        }
    }

    // ==================== GST REPORT ====================

    async sendGSTReport() {
        if (!this.ownerPhone) return { success: false, error: 'Owner phone not configured' }

        try {
            const bills = await realDataService.getBills()
            const gstRate = parseFloat(localStorage.getItem('kadai_default_gst_rate') || '5') / 100

            let totalSales = 0
            let totalGST = 0

            bills.forEach(bill => {
                const taxable = bill.subtotal || bill.total / (1 + gstRate)
                totalSales += taxable
                totalGST += taxable * gstRate
            })

            const cgst = totalGST / 2
            const sgst = totalGST / 2

            const message = `📋 *GST SUMMARY REPORT*
📍 ${this.storeName}
📅 ${new Date().toLocaleDateString('en-IN')}

━━━━━━━━━━━━━━━━━━━━

💰 *TAXABLE SALES*: ₹${Math.round(totalSales).toLocaleString()}

*GST BREAKDOWN*
• CGST (${(gstRate * 50).toFixed(1)}%): ₹${Math.round(cgst).toLocaleString()}
• SGST (${(gstRate * 50).toFixed(1)}%): ₹${Math.round(sgst).toLocaleString()}

━━━━━━━━━━━━━━━━━━━━

📊 *TOTAL GST*: *₹${Math.round(totalGST).toLocaleString()}*

_Generated by KadaiGPT AI_ 🤖`

            whatsappService.openWhatsApp(this.ownerPhone, message)
            return { success: true }
        } catch (error) {
            return { success: false, error: error.message }
        }
    }
}

// Export singleton
const whatsappAgentService = new WhatsAppAgentService()
export default whatsappAgentService
